# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - script: echo Hi everybody!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: Pulumi@1
  inputs:
    azureSubscription: 'zachlab(1d3a3cb3-fe4d-447c-8275-68f63a3e7809)'
    command: 'preview'
    loginArgs: '--local'
    cwd: './aws-typescript'
    stack: 'zach-perkins/aws-typescript/dev'
    createPrComment: true